# Generated by Django 4.2.8 on 2023-12-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0002_processor_historicalprocessor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprocessor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='id',
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='name',
            field=models.TextField(blank=True, help_text='The name of the processor.', null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='product_id',
            field=models.IntegerField(db_index=True, default=1, help_text='The product ID of the processor.', verbose_name='Product ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processor',
            name='name',
            field=models.TextField(blank=True, help_text='The name of the processor.', null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='processor',
            name='product_id',
            field=models.IntegerField(default=2, help_text='The product ID of the processor.', primary_key=True, serialize=False, verbose_name='Product ID'),
            preserve_default=False,
        ),
    ]
