# Generated by Django 4.2.8 on 2023-12-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0003_remove_historicalprocessor_id_remove_processor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprocessor',
            name='l3_cache',
        ),
        migrations.RemoveField(
            model_name='historicalprocessor',
            name='mipi_soundwire_technology',
        ),
        migrations.RemoveField(
            model_name='historicalprocessor',
            name='socket_supported',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='l3_cache',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='mipi_soundwire_technology',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='socket_supported',
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='adaptive_boost_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Adaptive Boost Technology is supported.', null=True, verbose_name='Intel Adaptive Boost Technology'),
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='integrated_ide',
            field=models.BooleanField(blank=True, help_text='Integrated development environment', null=True, verbose_name='Integrated IDE'),
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='l2_cache',
            field=models.TextField(blank=True, help_text='The L2 cache the processor has.', null=True, verbose_name='L2 Cache'),
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='max_assured_power',
            field=models.IntegerField(blank=True, help_text='The maximum assured power of the processor. In watts.', null=True, verbose_name='Maximum Assured Power'),
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='min_assured_power',
            field=models.IntegerField(blank=True, help_text='The minimum assured power of the processor. In watts.', null=True, verbose_name='Minimum Assured Power'),
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='mipi_soundwire_version',
            field=models.FloatField(blank=True, help_text='The MIPI SoundWire version the processor supports.', null=True, verbose_name='MIPI SoundWire Version'),
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='single_efficiency_core_turbo_frequency',
            field=models.IntegerField(blank=True, help_text='How many hertz a single E-core can reach.', null=True, verbose_name='Single E-core Turbo Frequency'),
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='single_performance_core_turbo_frequency',
            field=models.IntegerField(blank=True, help_text='How many hertz a single P-core can reach.', null=True, verbose_name='Single P-core Turbo Frequency'),
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='sockets_supported',
            field=models.TextField(blank=True, help_text='Sockets the processor supports.', null=True, verbose_name='Sockets Supported'),
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='thread_director',
            field=models.BooleanField(blank=True, help_text='Monitors the runtime instruction mix of each thread and the state of each core with nanosecond precision.', null=True, verbose_name='Intel Thread Director'),
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='usb_configuration',
            field=models.TextField(blank=True, help_text='The amount and generation the CPU supports.', null=True, verbose_name='USB Configuration'),
        ),
        migrations.AddField(
            model_name='processor',
            name='adaptive_boost_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Adaptive Boost Technology is supported.', null=True, verbose_name='Intel Adaptive Boost Technology'),
        ),
        migrations.AddField(
            model_name='processor',
            name='integrated_ide',
            field=models.BooleanField(blank=True, help_text='Integrated development environment', null=True, verbose_name='Integrated IDE'),
        ),
        migrations.AddField(
            model_name='processor',
            name='l2_cache',
            field=models.TextField(blank=True, help_text='The L2 cache the processor has.', null=True, verbose_name='L2 Cache'),
        ),
        migrations.AddField(
            model_name='processor',
            name='max_assured_power',
            field=models.IntegerField(blank=True, help_text='The maximum assured power of the processor. In watts.', null=True, verbose_name='Maximum Assured Power'),
        ),
        migrations.AddField(
            model_name='processor',
            name='min_assured_power',
            field=models.IntegerField(blank=True, help_text='The minimum assured power of the processor. In watts.', null=True, verbose_name='Minimum Assured Power'),
        ),
        migrations.AddField(
            model_name='processor',
            name='mipi_soundwire_version',
            field=models.FloatField(blank=True, help_text='The MIPI SoundWire version the processor supports.', null=True, verbose_name='MIPI SoundWire Version'),
        ),
        migrations.AddField(
            model_name='processor',
            name='single_efficiency_core_turbo_frequency',
            field=models.IntegerField(blank=True, help_text='How many hertz a single E-core can reach.', null=True, verbose_name='Single E-core Turbo Frequency'),
        ),
        migrations.AddField(
            model_name='processor',
            name='single_performance_core_turbo_frequency',
            field=models.IntegerField(blank=True, help_text='How many hertz a single P-core can reach.', null=True, verbose_name='Single P-core Turbo Frequency'),
        ),
        migrations.AddField(
            model_name='processor',
            name='sockets_supported',
            field=models.TextField(blank=True, help_text='Sockets the processor supports.', null=True, verbose_name='Sockets Supported'),
        ),
        migrations.AddField(
            model_name='processor',
            name='thread_director',
            field=models.BooleanField(blank=True, help_text='Monitors the runtime instruction mix of each thread and the state of each core with nanosecond precision.', null=True, verbose_name='Intel Thread Director'),
        ),
        migrations.AddField(
            model_name='processor',
            name='usb_configuration',
            field=models.TextField(blank=True, help_text='The amount and generation the CPU supports.', null=True, verbose_name='USB Configuration'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='_64_bit',
            field=models.BooleanField(blank=True, help_text='Whether 64-bit is supported. Also called EM64T (Extended Memory 64 Technology).', null=True, verbose_name='64-bit'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='deep_learning_boost',
            field=models.BooleanField(blank=True, help_text='Whether Intel Deep Learning Boost (Intel DL Boost) is supported.', null=True, verbose_name='Intel Deep Learning Boost (Intel DL Boost)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='demand_based_switching',
            field=models.BooleanField(blank=True, help_text='Whether Intel Demand Based Switching is supported.', null=True, verbose_name='Intel Demand Based Switching'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='enhanced_speedstep_technology',
            field=models.BooleanField(blank=True, help_text='Allows the clock speed to be dynamically changed (to different P-states) by software.', null=True, verbose_name='Enhanced Intel SpeedStep Technology'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='gaussian_neural_accelerator',
            field=models.BooleanField(blank=True, help_text='Whether gaussian & neural accelerator is supported.', null=True, verbose_name='Intel Gaussian & Neural Accelerator'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='high_definition_audio',
            field=models.BooleanField(blank=True, help_text='Whether Intel High Definition Audio is supported.', null=True, verbose_name='Intel High Definition Audio'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='image_processing_unit',
            field=models.BooleanField(blank=True, help_text='Whether Intel Image Processing Unit is supported.', null=True, verbose_name='Intel Image Processing Unit'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='max_cpu_configuration',
            field=models.TextField(blank=True, help_text='How many CPUs you can have in a configuration.', null=True, verbose_name='Max CPU Configuration'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='optane_supported',
            field=models.BooleanField(blank=True, help_text='Whether Intel Optane is supported.', null=True, verbose_name='Intel Optane supported'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='resource_director_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Resource Director Technology (Intel RDT) is supported.', null=True, verbose_name='Intel Resource Director Technology (Intel RDT)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='smart_sound_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Smart Sound Technology is supported.', null=True, verbose_name='Intel Smart Sound Technology'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='t_case',
            field=models.IntegerField(blank=True, help_text='The maximum temperature allowed at the processor Integrated Heat Spreader (IHS).', null=True, verbose_name='T Case'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='t_junction',
            field=models.IntegerField(blank=True, help_text='The highest temperature the processor can reach without damaging it. In celsius.', null=True, verbose_name='T Junction'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='thermal_monitoring_technologies',
            field=models.BooleanField(blank=True, help_text='Allows the processor to maintain optimal temperature by regulating voltage and frequency.', null=True, verbose_name='Thermal Monitoring Technologies'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='thermal_velocity_boost',
            field=models.BooleanField(blank=True, help_text='Whether Intel Thermal Velocity Boost is supported.', null=True, verbose_name='Intel Thermal Velocity Boost'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='time_coordinated_computing',
            field=models.BooleanField(blank=True, help_text='Whether Intel Time Coordinated Computing (Intel TCC) is supported.', null=True, verbose_name='Intel Time Coordinated Computing (Intel TCC)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='transactional_synchronization_extensions',
            field=models.BooleanField(blank=True, help_text='Whether Intel TSX-NI is supported.', null=True, verbose_name='Intel TSX-NI'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='turbo_boost_technology',
            field=models.TextField(blank=True, help_text='Intel Turbo Boost version used', null=True, verbose_name='Intel Turbo Boost version'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='uart',
            field=models.TextField(blank=True, help_text='Universal asynchronous receiver-transmitter', null=True, verbose_name='UART'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='volume_management_device',
            field=models.BooleanField(blank=True, help_text='Enables direct control and management of NVMe SSDs from the PCIe bus without additional hardware adaptors', null=True, verbose_name='Intel Volume Management Device (VMD)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='wake_on_voice',
            field=models.BooleanField(blank=True, help_text='Whether Intel Wake on Voice is supported.', null=True, verbose_name='Intel Wake on Voice'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='_64_bit',
            field=models.BooleanField(blank=True, help_text='Whether 64-bit is supported. Also called EM64T (Extended Memory 64 Technology).', null=True, verbose_name='64-bit'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='deep_learning_boost',
            field=models.BooleanField(blank=True, help_text='Whether Intel Deep Learning Boost (Intel DL Boost) is supported.', null=True, verbose_name='Intel Deep Learning Boost (Intel DL Boost)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='demand_based_switching',
            field=models.BooleanField(blank=True, help_text='Whether Intel Demand Based Switching is supported.', null=True, verbose_name='Intel Demand Based Switching'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='enhanced_speedstep_technology',
            field=models.BooleanField(blank=True, help_text='Allows the clock speed to be dynamically changed (to different P-states) by software.', null=True, verbose_name='Enhanced Intel SpeedStep Technology'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='gaussian_neural_accelerator',
            field=models.BooleanField(blank=True, help_text='Whether gaussian & neural accelerator is supported.', null=True, verbose_name='Intel Gaussian & Neural Accelerator'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='high_definition_audio',
            field=models.BooleanField(blank=True, help_text='Whether Intel High Definition Audio is supported.', null=True, verbose_name='Intel High Definition Audio'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='image_processing_unit',
            field=models.BooleanField(blank=True, help_text='Whether Intel Image Processing Unit is supported.', null=True, verbose_name='Intel Image Processing Unit'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='max_cpu_configuration',
            field=models.TextField(blank=True, help_text='How many CPUs you can have in a configuration.', null=True, verbose_name='Max CPU Configuration'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='optane_supported',
            field=models.BooleanField(blank=True, help_text='Whether Intel Optane is supported.', null=True, verbose_name='Intel Optane supported'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='resource_director_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Resource Director Technology (Intel RDT) is supported.', null=True, verbose_name='Intel Resource Director Technology (Intel RDT)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='smart_sound_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Smart Sound Technology is supported.', null=True, verbose_name='Intel Smart Sound Technology'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='t_case',
            field=models.IntegerField(blank=True, help_text='The maximum temperature allowed at the processor Integrated Heat Spreader (IHS).', null=True, verbose_name='T Case'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='t_junction',
            field=models.IntegerField(blank=True, help_text='The highest temperature the processor can reach without damaging it. In celsius.', null=True, verbose_name='T Junction'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='thermal_monitoring_technologies',
            field=models.BooleanField(blank=True, help_text='Allows the processor to maintain optimal temperature by regulating voltage and frequency.', null=True, verbose_name='Thermal Monitoring Technologies'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='thermal_velocity_boost',
            field=models.BooleanField(blank=True, help_text='Whether Intel Thermal Velocity Boost is supported.', null=True, verbose_name='Intel Thermal Velocity Boost'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='time_coordinated_computing',
            field=models.BooleanField(blank=True, help_text='Whether Intel Time Coordinated Computing (Intel TCC) is supported.', null=True, verbose_name='Intel Time Coordinated Computing (Intel TCC)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='transactional_synchronization_extensions',
            field=models.BooleanField(blank=True, help_text='Whether Intel TSX-NI is supported.', null=True, verbose_name='Intel TSX-NI'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='turbo_boost_technology',
            field=models.TextField(blank=True, help_text='Intel Turbo Boost version used', null=True, verbose_name='Intel Turbo Boost version'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='uart',
            field=models.TextField(blank=True, help_text='Universal asynchronous receiver-transmitter', null=True, verbose_name='UART'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='volume_management_device',
            field=models.BooleanField(blank=True, help_text='Enables direct control and management of NVMe SSDs from the PCIe bus without additional hardware adaptors', null=True, verbose_name='Intel Volume Management Device (VMD)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='wake_on_voice',
            field=models.BooleanField(blank=True, help_text='Whether Intel Wake on Voice is supported.', null=True, verbose_name='Intel Wake on Voice'),
        ),
    ]
