# Generated by Django 4.2.8 on 2023-12-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0004_remove_historicalprocessor_l3_cache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocessor',
            name='hardware_shield',
            field=models.BooleanField(blank=True, help_text='Whether Intel Hardware Shield is supported.', null=True, verbose_name='Intel Hardware Shield Eligibility'),
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='network_interfaces',
            field=models.TextField(blank=True, help_text='The network interfaces the processor has.', null=True, verbose_name='Network Interfaces'),
        ),
        migrations.AddField(
            model_name='historicalprocessor',
            name='standard_manageability',
            field=models.BooleanField(blank=True, help_text='Whether Intel Standard Manageability (ISM) is supported.', null=True, verbose_name='Intel Standard Manageability (ISM)'),
        ),
        migrations.AddField(
            model_name='processor',
            name='hardware_shield',
            field=models.BooleanField(blank=True, help_text='Whether Intel Hardware Shield is supported.', null=True, verbose_name='Intel Hardware Shield Eligibility'),
        ),
        migrations.AddField(
            model_name='processor',
            name='network_interfaces',
            field=models.TextField(blank=True, help_text='The network interfaces the processor has.', null=True, verbose_name='Network Interfaces'),
        ),
        migrations.AddField(
            model_name='processor',
            name='standard_manageability',
            field=models.BooleanField(blank=True, help_text='Whether Intel Standard Manageability (ISM) is supported.', null=True, verbose_name='Intel Standard Manageability (ISM)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='_4k_support',
            field=models.TextField(blank=True, help_text='Whether 4K is supported.', null=True, verbose_name='4K Support'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='active_management_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Active Management Technology (AMT) is supported.', null=True, verbose_name='Intel Active Management Technology (AMT)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='aes_new_instructions',
            field=models.BooleanField(blank=True, help_text='Whether Intel AES New Instructions is supported.', null=True, verbose_name='Intel AES New Instructions'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='boot_guard',
            field=models.BooleanField(blank=True, help_text='Whether Intel Boot Guard is supported.', null=True, verbose_name='Intel Boot Guard'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='control_flow_enforcement_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Control-flow Enforcement Technology is supported.', null=True, verbose_name='Intel Control-flow Enforcement Technology'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='crypto_acceleration',
            field=models.BooleanField(blank=True, help_text='Whether Intel Crypto Acceleration is supported.', null=True, verbose_name='Intel Crypto Acceleration'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='execute_disable_bit',
            field=models.BooleanField(blank=True, help_text='The Execute Disable Bit is a hardware-based security feature that can reduce exposure to viruses and malicious-code attacks, and prevent harmful software from executing and propagating on the server or network.', null=True, verbose_name='Execute Disable Bit'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='identity_protection_technology',
            field=models.BooleanField(blank=True, help_text='Intel Identity Protection Technology generates a unique PC number and a six-digit code for web authentication.', null=True, verbose_name='Intel Identity Protection Technology'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='maximum_enclave_size_for_sgx',
            field=models.IntegerField(blank=True, help_text='How many bytes the Enclave Page Cache (EPC) can be.', null=True, verbose_name='Default Maximum Enclave Page Cache (EPC) Size for Intel SGX'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='mode_based_execute_control',
            field=models.BooleanField(blank=True, help_text='Whether Mode-based Execute Control (MBE) is supported.', null=True, verbose_name='Mode-based Execute Control (MBE)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='one_click_recovery',
            field=models.BooleanField(blank=True, help_text='Whether Intel One-click Recovery is supported.', null=True, verbose_name='Intel One-click Recovery'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='os_guard',
            field=models.BooleanField(blank=True, help_text='Whether Intel OS Guard is supported.', null=True, verbose_name='Intel OS Guard'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='platform_firmware_resilience',
            field=models.BooleanField(blank=True, help_text='Whether Intel Platform Firmware Resilience Support (Intel PFR) is supported.', null=True, verbose_name='Intel Platform Firmware Resilience Support (Intel PFR)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='quick_assist_software_acceleration',
            field=models.BooleanField(blank=True, help_text='Offloads data compression and decompression, encrypt and decrypt, and public key data encryption tasks from the CPU cores', null=True, verbose_name='Intel QuickAssist Software Acceleration'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='remote_platform_erase',
            field=models.BooleanField(blank=True, help_text='Whether Intel Remote Platform Erase (RPE) is supported.', null=True, verbose_name='Intel Remote Platform Erase (RPE)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='software_guard_extensions',
            field=models.TextField(blank=True, help_text='Whether Intel Software Guard Extensions (Intel SGX) is supported.', null=True, verbose_name='Intel Software Guard Extensions (Intel SGX)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='threat_detection_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Threat Detection Technology (TDT) is supported.', null=True, verbose_name='Intel Threat Detection Technology (TDT)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='total_memory_encryption',
            field=models.BooleanField(blank=True, help_text='Whether Intel Total Memory Encryption (Intel TME) is supported.', null=True, verbose_name='Intel Total Memory Encryption (Intel TME)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='total_memory_encryption_multi_key',
            field=models.BooleanField(blank=True, help_text='Whether Intel Total Memory Encryption - Multi Key is supported.', null=True, verbose_name='Intel Total Memory Encryption - Multi Key'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='trusted_execution_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Trusted Execution Technology (Intel TXT, formerly known as LaGrande Technology) is supported.', null=True, verbose_name='Intel Trusted Execution Technology (Intel TXT, formerly known as LaGrande Technology)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='virtualization_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Virtualization Technology (VT-x) is supported.', null=True, verbose_name='Intel Virtualization Technology (VT-x)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='virtualization_technology_with_redirect_protection',
            field=models.BooleanField(blank=True, help_text='Whether Intel Virtualization Technology with Redirect Protection (VT-rp) is supported.', null=True, verbose_name='Intel Virtualization Technology with Redirect Protection (VT-rp)'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='vpro_eligibility',
            field=models.TextField(blank=True, help_text='Whether Intel vPro is supported.', null=True, verbose_name='Intel vPro Eligibility'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='_4k_support',
            field=models.TextField(blank=True, help_text='Whether 4K is supported.', null=True, verbose_name='4K Support'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='active_management_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Active Management Technology (AMT) is supported.', null=True, verbose_name='Intel Active Management Technology (AMT)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='aes_new_instructions',
            field=models.BooleanField(blank=True, help_text='Whether Intel AES New Instructions is supported.', null=True, verbose_name='Intel AES New Instructions'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='boot_guard',
            field=models.BooleanField(blank=True, help_text='Whether Intel Boot Guard is supported.', null=True, verbose_name='Intel Boot Guard'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='control_flow_enforcement_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Control-flow Enforcement Technology is supported.', null=True, verbose_name='Intel Control-flow Enforcement Technology'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='crypto_acceleration',
            field=models.BooleanField(blank=True, help_text='Whether Intel Crypto Acceleration is supported.', null=True, verbose_name='Intel Crypto Acceleration'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='execute_disable_bit',
            field=models.BooleanField(blank=True, help_text='The Execute Disable Bit is a hardware-based security feature that can reduce exposure to viruses and malicious-code attacks, and prevent harmful software from executing and propagating on the server or network.', null=True, verbose_name='Execute Disable Bit'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='identity_protection_technology',
            field=models.BooleanField(blank=True, help_text='Intel Identity Protection Technology generates a unique PC number and a six-digit code for web authentication.', null=True, verbose_name='Intel Identity Protection Technology'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='maximum_enclave_size_for_sgx',
            field=models.IntegerField(blank=True, help_text='How many bytes the Enclave Page Cache (EPC) can be.', null=True, verbose_name='Default Maximum Enclave Page Cache (EPC) Size for Intel SGX'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='mode_based_execute_control',
            field=models.BooleanField(blank=True, help_text='Whether Mode-based Execute Control (MBE) is supported.', null=True, verbose_name='Mode-based Execute Control (MBE)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='one_click_recovery',
            field=models.BooleanField(blank=True, help_text='Whether Intel One-click Recovery is supported.', null=True, verbose_name='Intel One-click Recovery'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='os_guard',
            field=models.BooleanField(blank=True, help_text='Whether Intel OS Guard is supported.', null=True, verbose_name='Intel OS Guard'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='platform_firmware_resilience',
            field=models.BooleanField(blank=True, help_text='Whether Intel Platform Firmware Resilience Support (Intel PFR) is supported.', null=True, verbose_name='Intel Platform Firmware Resilience Support (Intel PFR)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='quick_assist_software_acceleration',
            field=models.BooleanField(blank=True, help_text='Offloads data compression and decompression, encrypt and decrypt, and public key data encryption tasks from the CPU cores', null=True, verbose_name='Intel QuickAssist Software Acceleration'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='remote_platform_erase',
            field=models.BooleanField(blank=True, help_text='Whether Intel Remote Platform Erase (RPE) is supported.', null=True, verbose_name='Intel Remote Platform Erase (RPE)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='software_guard_extensions',
            field=models.TextField(blank=True, help_text='Whether Intel Software Guard Extensions (Intel SGX) is supported.', null=True, verbose_name='Intel Software Guard Extensions (Intel SGX)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='threat_detection_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Threat Detection Technology (TDT) is supported.', null=True, verbose_name='Intel Threat Detection Technology (TDT)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='total_memory_encryption',
            field=models.BooleanField(blank=True, help_text='Whether Intel Total Memory Encryption (Intel TME) is supported.', null=True, verbose_name='Intel Total Memory Encryption (Intel TME)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='total_memory_encryption_multi_key',
            field=models.BooleanField(blank=True, help_text='Whether Intel Total Memory Encryption - Multi Key is supported.', null=True, verbose_name='Intel Total Memory Encryption - Multi Key'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='trusted_execution_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Trusted Execution Technology (Intel TXT, formerly known as LaGrande Technology) is supported.', null=True, verbose_name='Intel Trusted Execution Technology (Intel TXT, formerly known as LaGrande Technology)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='virtualization_technology',
            field=models.BooleanField(blank=True, help_text='Whether Intel Virtualization Technology (VT-x) is supported.', null=True, verbose_name='Intel Virtualization Technology (VT-x)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='virtualization_technology_with_redirect_protection',
            field=models.BooleanField(blank=True, help_text='Whether Intel Virtualization Technology with Redirect Protection (VT-rp) is supported.', null=True, verbose_name='Intel Virtualization Technology with Redirect Protection (VT-rp)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='vpro_eligibility',
            field=models.TextField(blank=True, help_text='Whether Intel vPro is supported.', null=True, verbose_name='Intel vPro Eligibility'),
        ),
    ]
