# Generated by Django 4.2.8 on 2023-12-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0006_alter_historicalprocessor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processor',
            options={'ordering': ['-created'], 'verbose_name': 'Intel processor', 'verbose_name_plural': 'Intel processors'},
        ),
        migrations.RenameField(
            model_name='arkfilterdata',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='arkfilterdata',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='processor',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='processor',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='historicalarkfilterdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalarkfilterdata',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalprocessor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalprocessor',
            name='updated_at',
        ),
    ]
