# Generated by Django 4.2.8 on 2023-12-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0007_alter_processor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arkfilterdata',
            options={'ordering': ['-created'], 'verbose_name': 'Intel ARK Filter Data', 'verbose_name_plural': 'Intel ARK Filter Data'},
        ),
    ]
