# Generated by Django 4.2.8 on 2023-12-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0008_alter_arkfilterdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocessor',
            name='base_frequency',
            field=models.BigIntegerField(blank=True, help_text='The base frequency the processor can reach. In hertz.', null=True, verbose_name='Base Frequency'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='bus_speed',
            field=models.TextField(blank=True, help_text='The bus speed of the processor. In giga-transfers per second.', null=True, verbose_name='Bus Speed'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='configurable_tdp_down_frequency',
            field=models.BigIntegerField(blank=True, help_text='The configurable TDP-down frequency of the processor. In hertz.', null=True, verbose_name='Configurable TDP-down Frequency'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='e_core_base_frequency',
            field=models.BigIntegerField(blank=True, help_text='The base frequency of the E-Core. In hertz.', null=True, verbose_name='E-Core Base Frequency'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='graphics_base_frequency',
            field=models.BigIntegerField(blank=True, help_text='The graphics base frequency the processor has. In hertz.', null=True, verbose_name='Graphics Base Frequency'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='graphics_max_dynamic_frequency',
            field=models.BigIntegerField(blank=True, help_text='The graphics max dynamic frequency the processor has. In hertz.', null=True, verbose_name='Graphics Max Dynamic Frequency'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='max_memory_size',
            field=models.BigIntegerField(blank=True, help_text='The maximum memory size the processor supports.', null=True, verbose_name='Max Memory Size'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='max_turbo_frequency',
            field=models.BigIntegerField(blank=True, help_text='The maximum turbo frequency the processor can reach. In hertz.', null=True, verbose_name='Max Turbo Frequency'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='p_core_base_frequency',
            field=models.BigIntegerField(blank=True, help_text='The base frequency of the P-Core. In hertz.', null=True, verbose_name='P-Core Base Frequency'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='single_efficiency_core_turbo_frequency',
            field=models.BigIntegerField(blank=True, help_text='How many hertz a single E-core can reach.', null=True, verbose_name='Single E-core Turbo Frequency'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='single_performance_core_turbo_frequency',
            field=models.BigIntegerField(blank=True, help_text='How many hertz a single P-core can reach.', null=True, verbose_name='Single P-core Turbo Frequency'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='turbo_boost_max_technology_3_0_frequency',
            field=models.BigIntegerField(blank=True, help_text='The maximum turbo frequency the processor can reach. In hertz.', null=True, verbose_name='Turbo Boost Max Technology 3.0 Frequency'),
        ),
        migrations.AlterField(
            model_name='historicalprocessor',
            name='upi_speed',
            field=models.TextField(blank=True, help_text='The UPI speed of the processor. In giga-transfers per second.', null=True, verbose_name='UPI Speed'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='base_frequency',
            field=models.BigIntegerField(blank=True, help_text='The base frequency the processor can reach. In hertz.', null=True, verbose_name='Base Frequency'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='bus_speed',
            field=models.TextField(blank=True, help_text='The bus speed of the processor. In giga-transfers per second.', null=True, verbose_name='Bus Speed'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='configurable_tdp_down_frequency',
            field=models.BigIntegerField(blank=True, help_text='The configurable TDP-down frequency of the processor. In hertz.', null=True, verbose_name='Configurable TDP-down Frequency'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='e_core_base_frequency',
            field=models.BigIntegerField(blank=True, help_text='The base frequency of the E-Core. In hertz.', null=True, verbose_name='E-Core Base Frequency'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='graphics_base_frequency',
            field=models.BigIntegerField(blank=True, help_text='The graphics base frequency the processor has. In hertz.', null=True, verbose_name='Graphics Base Frequency'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='graphics_max_dynamic_frequency',
            field=models.BigIntegerField(blank=True, help_text='The graphics max dynamic frequency the processor has. In hertz.', null=True, verbose_name='Graphics Max Dynamic Frequency'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='max_memory_size',
            field=models.BigIntegerField(blank=True, help_text='The maximum memory size the processor supports.', null=True, verbose_name='Max Memory Size'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='max_turbo_frequency',
            field=models.BigIntegerField(blank=True, help_text='The maximum turbo frequency the processor can reach. In hertz.', null=True, verbose_name='Max Turbo Frequency'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='p_core_base_frequency',
            field=models.BigIntegerField(blank=True, help_text='The base frequency of the P-Core. In hertz.', null=True, verbose_name='P-Core Base Frequency'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='single_efficiency_core_turbo_frequency',
            field=models.BigIntegerField(blank=True, help_text='How many hertz a single E-core can reach.', null=True, verbose_name='Single E-core Turbo Frequency'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='single_performance_core_turbo_frequency',
            field=models.BigIntegerField(blank=True, help_text='How many hertz a single P-core can reach.', null=True, verbose_name='Single P-core Turbo Frequency'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='turbo_boost_max_technology_3_0_frequency',
            field=models.BigIntegerField(blank=True, help_text='The maximum turbo frequency the processor can reach. In hertz.', null=True, verbose_name='Turbo Boost Max Technology 3.0 Frequency'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='upi_speed',
            field=models.TextField(blank=True, help_text='The UPI speed of the processor. In giga-transfers per second.', null=True, verbose_name='UPI Speed'),
        ),
    ]
