# Generated by Django 4.2.8 on 2023-12-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0011_alter_historicalprocessor_max_memory_bandwidth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocessor',
            name='turbo_boost_2_0_frequency',
            field=models.BigIntegerField(blank=True, help_text='The maximum turbo frequency the processor can reach. In hertz.', null=True, verbose_name='Turbo Boost 2.0 Frequency'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='turbo_boost_2_0_frequency',
            field=models.BigIntegerField(blank=True, help_text='The maximum turbo frequency the processor can reach. In hertz.', null=True, verbose_name='Turbo Boost 2.0 Frequency'),
        ),
    ]
