# Generated by Django 4.2.8 on 2023-12-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0012_alter_historicalprocessor_turbo_boost_2_0_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocessor',
            name='max_memory_speed',
            field=models.BigIntegerField(blank=True, help_text='The maximum memory speed the processor supports. In hertz.', null=True, verbose_name='Max Memory Speed'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='max_memory_speed',
            field=models.BigIntegerField(blank=True, help_text='The maximum memory speed the processor supports. In hertz.', null=True, verbose_name='Max Memory Speed'),
        ),
    ]
