# Generated by Django 4.2.8 on 2023-12-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0014_historicalprocessor_deep_learning_boost_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocessor',
            name='thermal_velocity_boost_frequency',
            field=models.BigIntegerField(blank=True, help_text='The thermal velocity boost frequency of the processor. In hertz.', null=True, verbose_name='Thermal Velocity Boost Frequency'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='thermal_velocity_boost_frequency',
            field=models.BigIntegerField(blank=True, help_text='The thermal velocity boost frequency of the processor. In hertz.', null=True, verbose_name='Thermal Velocity Boost Frequency'),
        ),
    ]
