# Generated by Django 4.2.8 on 2024-01-02 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0016_alter_historicalprocessor_maximum_enclave_size_for_sgx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprocessor',
            old_name='maximum_turbo_power',
            new_name='max_turbo_power',
        ),
        migrations.RenameField(
            model_name='processor',
            old_name='maximum_turbo_power',
            new_name='max_turbo_power',
        ),
    ]
