# Generated by Django 4.2.8 on 2024-01-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0018_historicalprocessor_slug_processor_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocessor',
            name='slug',
            field=models.SlugField(default='Unknown', help_text='Slug used for the URL.', verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processor',
            name='slug',
            field=models.SlugField(default='Unknown', help_text='Slug used for the URL.', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
