# Generated by Django 4.2.8 on 2024-01-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0019_alter_historicalprocessor_slug_alter_processor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocessor',
            name='name',
            field=models.TextField(blank=True, help_text='The name of the processor.', null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='name',
            field=models.TextField(blank=True, help_text='The name of the processor.', null=True, verbose_name='Name'),
        ),
    ]
