services:
  web:
    container_name: web
    image: ghcr.io/thelovinator1/panso:latest
    volumes:
      - /mnt/Fourteen/Docker/Panso/panso/logs:/var/log/nginx/
    restart: always
    networks:
      - tunnel
  tunnel:
    container_name: tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token $TUNNEL_TOKEN
    restart: always
    networks:
      - tunnel
    environment:
      - TUNNEL_URL=http://web:80
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    user: "1000:1000"
    ports:
      - 6379:6379
    command: /bin/sh -c 'redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes'
    volumes:
      - /mnt/Fourteen/Docker/Panso/Redis:/data
    networks:
      - redis
  postgres:
    container_name: postgres
    image: postgres:16
    user: "1000:1000"
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /mnt/Fourteen/Docker/Panso/Postgres:/var/lib/postgresql/data
    networks:
      - db

networks:
  tunnel:
    driver: bridge
  panso:
    driver: bridge
  redis:
    driver: bridge
  db:
    driver: bridge
