# Generated by Django 4.2.7 on 2023-12-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhallen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwebhallenproduct',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='WebhallenProduct',
        ),
        migrations.AlterModelOptions(
            name='historicalwebhallenjson',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Webhallen JSON', 'verbose_name_plural': 'historical Webhallen JSON Entries'},
        ),
        migrations.AlterModelOptions(
            name='webhallenjson',
            options={'verbose_name': 'Webhallen JSON', 'verbose_name_plural': 'Webhallen JSON Entries'},
        ),
        migrations.AlterModelTableComment(
            name='eans',
            table_comment='Table storing European Article Numbers (EANs)',
        ),
        migrations.AlterModelTableComment(
            name='sitemaparticle',
            table_comment='Table storing the https://www.webhallen.com/sitemap.article.xml sitemap',
        ),
        migrations.AlterModelTableComment(
            name='sitemapcampaign',
            table_comment='Table storing the https://www.webhallen.com/sitemap.campaign.xml sitemap',
        ),
        migrations.AlterModelTableComment(
            name='sitemapcampaignlist',
            table_comment='Table storing the https://www.webhallen.com/sitemap.campaignList.xml sitemap',
        ),
        migrations.AlterModelTableComment(
            name='sitemapcategory',
            table_comment='Table storing the https://www.webhallen.com/sitemap.category.xml sitemap',
        ),
        migrations.AlterModelTableComment(
            name='sitemaphome',
            table_comment='Table storing the https://www.webhallen.com/sitemap.home.xml sitemap',
        ),
        migrations.AlterModelTableComment(
            name='sitemapinfopages',
            table_comment='Table storing the https://www.webhallen.com/sitemap.infoPages.xml sitemap',
        ),
        migrations.AlterModelTableComment(
            name='sitemapmanufacturer',
            table_comment='Table storing the https://www.webhallen.com/sitemap.manufacturer.xml sitemap',
        ),
        migrations.AlterModelTableComment(
            name='sitemapproduct',
            table_comment='Table storing the https://www.webhallen.com/sitemap.product.xml sitemap',
        ),
        migrations.AlterModelTableComment(
            name='sitemaproot',
            table_comment='Table storing the https://www.webhallen.com/sitemap.xml sitemap',
        ),
        migrations.AlterModelTableComment(
            name='sitemapsection',
            table_comment='Table storing the https://www.webhallen.com/sitemap.section.xml sitemap',
        ),
        migrations.AlterModelTableComment(
            name='webhallenjson',
            table_comment='Table storing JSON data from Webhallen API',
        ),
        migrations.AlterModelTableComment(
            name='webhallensection',
            table_comment='Table storing Webhallen sections',
        ),
        migrations.DeleteModel(
            name='HistoricalWebhallenProduct',
        ),
    ]
