# Generated by Django 4.2.8 on 2023-12-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhallen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitemaparticle',
            options={'ordering': ['-loc'], 'verbose_name': 'Sitemap article', 'verbose_name_plural': 'Sitemap articles'},
        ),
        migrations.AlterModelOptions(
            name='sitemapcampaign',
            options={'ordering': ['-loc'], 'verbose_name': 'Sitemap campaign', 'verbose_name_plural': 'Sitemap campaigns'},
        ),
        migrations.AlterModelOptions(
            name='sitemapcampaignlist',
            options={'ordering': ['-loc'], 'verbose_name': 'Sitemap campaign list', 'verbose_name_plural': 'Sitemap campaign lists'},
        ),
        migrations.AlterModelOptions(
            name='sitemapcategory',
            options={'ordering': ['-loc'], 'verbose_name': 'Sitemap category', 'verbose_name_plural': 'Sitemap categories'},
        ),
        migrations.AlterModelOptions(
            name='sitemaphome',
            options={'ordering': ['-loc'], 'verbose_name': 'Sitemap home', 'verbose_name_plural': 'Sitemap homes'},
        ),
        migrations.AlterModelOptions(
            name='sitemapinfopages',
            options={'ordering': ['-loc'], 'verbose_name': 'Sitemap info page', 'verbose_name_plural': 'Sitemap info pages'},
        ),
        migrations.AlterModelOptions(
            name='sitemapmanufacturer',
            options={'ordering': ['-loc'], 'verbose_name': 'Sitemap manufacturer', 'verbose_name_plural': 'Sitemap manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='sitemapproduct',
            options={'ordering': ['-loc'], 'verbose_name': 'Sitemap product', 'verbose_name_plural': 'Sitemap products'},
        ),
        migrations.AlterModelOptions(
            name='sitemaproot',
            options={'ordering': ['-loc'], 'verbose_name': 'Sitemap root', 'verbose_name_plural': 'Sitemap roots'},
        ),
        migrations.AlterModelOptions(
            name='sitemapsection',
            options={'ordering': ['-loc'], 'verbose_name': 'Sitemap section', 'verbose_name_plural': 'Sitemap sections'},
        ),
        migrations.AlterModelOptions(
            name='webhallenjson',
            options={'ordering': ['-product_id'], 'verbose_name': 'Webhallen JSON', 'verbose_name_plural': 'Webhallen JSON Entries'},
        ),
        migrations.AlterModelOptions(
            name='webhallensection',
            options={'ordering': ['-section_id'], 'verbose_name': 'Webhallen section', 'verbose_name_plural': 'Webhallen sections'},
        ),
    ]
