# Generated by Django 4.2.7 on 2023-12-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhallen', '0002_remove_historicalwebhallenproduct_history_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eans',
        ),
        migrations.DeleteModel(
            name='HistoricalEans',
        ),
    ]
