# The name of your Worker. Alphanumeric and dashes only.
name = "webhallen"

# The path to the entrypoint of your Worker that will be executed.
main = "src/index.ts"

# A date in the form yyyy-mm-dd, which will be used to determine which version of the Workers runtime is used.
compatibility_date = "2023-10-30"
route = "webhallen.panso.se/*"

[placement]
mode = "smart"

[[ d1_databases ]]
binding = "DB"
database_name = "webhallen"
database_id = "1e784e2a-c5db-4710-842d-62de7e228b83"
