# Generated by Django 4.2.7 on 2023-11-19 01:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhallen",
            fields=[
                ("product_id", models.IntegerField(help_text="Product ID", primary_key=True, serialize=False)),
                ("product_json", models.JSONField(help_text="Product JSON")),
                ("created", models.DateTimeField(auto_now_add=True, help_text="Created")),
                ("updated", models.DateTimeField(auto_now=True, help_text="Updated")),
            ],
            options={
                "verbose_name": "Webhallen",
                "verbose_name_plural": "Webhallen",
            },
        ),
        migrations.CreateModel(
            name="HistoricalWebhallen",
            fields=[
                ("product_id", models.IntegerField(db_index=True, help_text="Product ID")),
                ("product_json", models.JSONField(help_text="Product JSON")),
                ("created", models.DateTimeField(blank=True, editable=False, help_text="Created")),
                ("updated", models.DateTimeField(blank=True, editable=False, help_text="Updated")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Webhallen",
                "verbose_name_plural": "historical Webhallen",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
