# Generated by Django 4.2.7 on 2023-11-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_webhallenproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwebhallenproduct',
            old_name='is_fyndware_of',
            new_name='fyndware_of',
        ),
        migrations.RenameField(
            model_name='webhallenproduct',
            old_name='is_fyndware_of',
            new_name='fyndware_of',
        ),
        migrations.RemoveField(
            model_name='historicalwebhallenproduct',
            name='energy_marking',
        ),
        migrations.RemoveField(
            model_name='historicalwebhallenproduct',
            name='images',
        ),
        migrations.RemoveField(
            model_name='webhallenproduct',
            name='energy_marking',
        ),
        migrations.RemoveField(
            model_name='webhallenproduct',
            name='images',
        ),
        migrations.AddField(
            model_name='historicalwebhallenproduct',
            name='energy_marking_label',
            field=models.TextField(blank=True, help_text='Energy rating label link'),
        ),
        migrations.AddField(
            model_name='historicalwebhallenproduct',
            name='energy_marking_rating',
            field=models.TextField(blank=True, help_text='Energy marking rating (F to A)'),
        ),
        migrations.AddField(
            model_name='historicalwebhallenproduct',
            name='fyndware_of_description',
            field=models.TextField(blank=True, help_text='Fyndware of description'),
        ),
        migrations.AddField(
            model_name='historicalwebhallenproduct',
            name='images_large',
            field=models.TextField(blank=True, help_text='Comma separated list of large images'),
        ),
        migrations.AddField(
            model_name='historicalwebhallenproduct',
            name='images_thumb',
            field=models.TextField(blank=True, help_text='Comma separated list of thumbnail images'),
        ),
        migrations.AddField(
            model_name='historicalwebhallenproduct',
            name='images_zoom',
            field=models.TextField(blank=True, help_text='Comma separated list of zoom images'),
        ),
        migrations.AddField(
            model_name='webhallenproduct',
            name='energy_marking_label',
            field=models.TextField(blank=True, help_text='Energy rating label link'),
        ),
        migrations.AddField(
            model_name='webhallenproduct',
            name='energy_marking_rating',
            field=models.TextField(blank=True, help_text='Energy marking rating (F to A)'),
        ),
        migrations.AddField(
            model_name='webhallenproduct',
            name='fyndware_of_description',
            field=models.TextField(blank=True, help_text='Fyndware of description'),
        ),
        migrations.AddField(
            model_name='webhallenproduct',
            name='images_large',
            field=models.TextField(blank=True, help_text='Comma separated list of large images'),
        ),
        migrations.AddField(
            model_name='webhallenproduct',
            name='images_thumb',
            field=models.TextField(blank=True, help_text='Comma separated list of thumbnail images'),
        ),
        migrations.AddField(
            model_name='webhallenproduct',
            name='images_zoom',
            field=models.TextField(blank=True, help_text='Comma separated list of zoom images'),
        ),
    ]
