# Generated by Django 4.2.7 on 2023-11-25 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_historicalwebhallenproduct_average_rating_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhallenSection',
            fields=[
                ('section_id', models.IntegerField(help_text='Section ID', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Updated')),
                ('meta_title', models.TextField(blank=True, help_text='Meta title', null=True)),
                ('active', models.BooleanField(help_text='Active', null=True)),
                ('icon', models.TextField(blank=True, help_text='Icon', null=True)),
                ('icon_url', models.URLField(blank=True, help_text='Icon URL', null=True)),
                ('name', models.TextField(blank=True, help_text='Name', null=True)),
                ('url', models.URLField(blank=True, help_text='URL', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalwebhallenproduct',
            name='highlighted_review_user_id',
            field=models.TextField(blank=True, help_text='Highlighted review user ID - Anonymous if anonymous', null=True),
        ),
        migrations.AlterField(
            model_name='webhallenproduct',
            name='highlighted_review_user_id',
            field=models.TextField(blank=True, help_text='Highlighted review user ID - Anonymous if anonymous', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalWebhallenSection',
            fields=[
                ('section_id', models.IntegerField(db_index=True, help_text='Section ID')),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Created')),
                ('updated', models.DateTimeField(blank=True, editable=False, help_text='Updated')),
                ('meta_title', models.TextField(blank=True, help_text='Meta title', null=True)),
                ('active', models.BooleanField(help_text='Active', null=True)),
                ('icon', models.TextField(blank=True, help_text='Icon', null=True)),
                ('icon_url', models.URLField(blank=True, help_text='Icon URL', null=True)),
                ('name', models.TextField(blank=True, help_text='Name', null=True)),
                ('url', models.URLField(blank=True, help_text='URL', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical webhallen section',
                'verbose_name_plural': 'historical webhallen sections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
