# Generated by Django 4.2.7 on 2023-11-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitemaparticle_sitemapcampaign_sitemapcampaignlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitemaparticle',
            name='priority',
            field=models.FloatField(help_text='Priority', null=True),
        ),
        migrations.AddField(
            model_name='historicalsitemapmanufacturer',
            name='priority',
            field=models.FloatField(help_text='Priority', null=True),
        ),
        migrations.AddField(
            model_name='historicalsitemapproduct',
            name='priority',
            field=models.FloatField(help_text='Priority', null=True),
        ),
        migrations.AddField(
            model_name='sitemaparticle',
            name='priority',
            field=models.FloatField(help_text='Priority', null=True),
        ),
        migrations.AddField(
            model_name='sitemapmanufacturer',
            name='priority',
            field=models.FloatField(help_text='Priority', null=True),
        ),
        migrations.AddField(
            model_name='sitemapproduct',
            name='priority',
            field=models.FloatField(help_text='Priority', null=True),
        ),
    ]
