# Generated by Django 4.2.7 on 2023-11-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_historicalsitemaparticle_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsitemaparticle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sitemap article', 'verbose_name_plural': 'historical Sitemap articles'},
        ),
        migrations.AlterModelOptions(
            name='historicalsitemapcampaign',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sitemap campaign', 'verbose_name_plural': 'historical Sitemap campaigns'},
        ),
        migrations.AlterModelOptions(
            name='historicalsitemapcampaignlist',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sitemap campaign list', 'verbose_name_plural': 'historical Sitemap campaign lists'},
        ),
        migrations.AlterModelOptions(
            name='historicalsitemapcategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sitemap category', 'verbose_name_plural': 'historical Sitemap categories'},
        ),
        migrations.AlterModelOptions(
            name='historicalsitemaphome',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sitemap home', 'verbose_name_plural': 'historical Sitemap homes'},
        ),
        migrations.AlterModelOptions(
            name='historicalsitemapinfopages',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sitemap info page', 'verbose_name_plural': 'historical Sitemap info pages'},
        ),
        migrations.AlterModelOptions(
            name='historicalsitemapmanufacturer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sitemap manufacturer', 'verbose_name_plural': 'historical Sitemap manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='historicalsitemapproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sitemap product', 'verbose_name_plural': 'historical Sitemap products'},
        ),
        migrations.AlterModelOptions(
            name='historicalsitemaproot',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sitemap root', 'verbose_name_plural': 'historical Sitemap roots'},
        ),
        migrations.AlterModelOptions(
            name='historicalsitemapsection',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sitemap section', 'verbose_name_plural': 'historical Sitemap sections'},
        ),
        migrations.AlterModelOptions(
            name='historicalwebhallenproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Webhallen product', 'verbose_name_plural': 'historical Webhallen products'},
        ),
        migrations.AlterModelOptions(
            name='historicalwebhallensection',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Webhallen section', 'verbose_name_plural': 'historical Webhallen sections'},
        ),
        migrations.AlterModelOptions(
            name='sitemaparticle',
            options={'verbose_name': 'Sitemap article', 'verbose_name_plural': 'Sitemap articles'},
        ),
        migrations.AlterModelOptions(
            name='sitemapcampaign',
            options={'verbose_name': 'Sitemap campaign', 'verbose_name_plural': 'Sitemap campaigns'},
        ),
        migrations.AlterModelOptions(
            name='sitemapcampaignlist',
            options={'verbose_name': 'Sitemap campaign list', 'verbose_name_plural': 'Sitemap campaign lists'},
        ),
        migrations.AlterModelOptions(
            name='sitemapcategory',
            options={'verbose_name': 'Sitemap category', 'verbose_name_plural': 'Sitemap categories'},
        ),
        migrations.AlterModelOptions(
            name='sitemaphome',
            options={'verbose_name': 'Sitemap home', 'verbose_name_plural': 'Sitemap homes'},
        ),
        migrations.AlterModelOptions(
            name='sitemapinfopages',
            options={'verbose_name': 'Sitemap info page', 'verbose_name_plural': 'Sitemap info pages'},
        ),
        migrations.AlterModelOptions(
            name='sitemapmanufacturer',
            options={'verbose_name': 'Sitemap manufacturer', 'verbose_name_plural': 'Sitemap manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='sitemapproduct',
            options={'verbose_name': 'Sitemap product', 'verbose_name_plural': 'Sitemap products'},
        ),
        migrations.AlterModelOptions(
            name='sitemaproot',
            options={'verbose_name': 'Sitemap root', 'verbose_name_plural': 'Sitemap roots'},
        ),
        migrations.AlterModelOptions(
            name='sitemapsection',
            options={'verbose_name': 'Sitemap section', 'verbose_name_plural': 'Sitemap sections'},
        ),
        migrations.AlterModelOptions(
            name='webhallenproduct',
            options={'verbose_name': 'Webhallen product', 'verbose_name_plural': 'Webhallen products'},
        ),
        migrations.AlterModelOptions(
            name='webhallensection',
            options={'verbose_name': 'Webhallen section', 'verbose_name_plural': 'Webhallen sections'},
        ),
        migrations.RemoveField(
            model_name='historicalsitemaparticle',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalsitemaparticle',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='historicalsitemapcampaign',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalsitemapcampaign',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='historicalsitemapcampaignlist',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalsitemapcampaignlist',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='historicalsitemapcategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalsitemapcategory',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='historicalsitemaphome',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalsitemaphome',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='historicalsitemapinfopages',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalsitemapinfopages',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='historicalsitemapmanufacturer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalsitemapmanufacturer',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='historicalsitemapproduct',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalsitemapproduct',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='historicalsitemaproot',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalsitemaproot',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='historicalsitemapsection',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalsitemapsection',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='historicalwebhallenjson',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalwebhallenjson',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='historicalwebhallenproduct',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalwebhallenproduct',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='historicalwebhallensection',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalwebhallensection',
            name='updated',
        ),
        migrations.AlterModelTable(
            name='historicalsitemaparticle',
            table='webhallen_sitemap_article_history',
        ),
        migrations.AlterModelTable(
            name='historicalsitemapcampaign',
            table='webhallen_sitemap_campaign_history',
        ),
        migrations.AlterModelTable(
            name='historicalsitemapcampaignlist',
            table='webhallen_sitemap_campaign_list_history',
        ),
        migrations.AlterModelTable(
            name='historicalsitemapcategory',
            table='webhallen_sitemap_category_history',
        ),
        migrations.AlterModelTable(
            name='historicalsitemaphome',
            table='webhallen_sitemap_home_history',
        ),
        migrations.AlterModelTable(
            name='historicalsitemapinfopages',
            table='webhallen_sitemap_info_pages_history',
        ),
        migrations.AlterModelTable(
            name='historicalsitemapmanufacturer',
            table='webhallen_sitemap_manufacturer_history',
        ),
        migrations.AlterModelTable(
            name='historicalsitemapproduct',
            table='webhallen_sitemap_product_history',
        ),
        migrations.AlterModelTable(
            name='historicalsitemaproot',
            table='webhallen_sitemap_root_history',
        ),
        migrations.AlterModelTable(
            name='historicalsitemapsection',
            table='webhallen_sitemap_section_history',
        ),
        migrations.AlterModelTable(
            name='historicalwebhallenjson',
            table='webhallen_history',
        ),
        migrations.AlterModelTable(
            name='historicalwebhallenproduct',
            table='webhallen_product_history',
        ),
        migrations.AlterModelTable(
            name='historicalwebhallensection',
            table='webhallen_section_history',
        ),
        migrations.AlterModelTable(
            name='sitemaparticle',
            table='webhallen_sitemap_article',
        ),
        migrations.AlterModelTable(
            name='sitemapcampaign',
            table='webhallen_sitemap_campaign',
        ),
        migrations.AlterModelTable(
            name='sitemapcampaignlist',
            table='webhallen_sitemap_campaign_list',
        ),
        migrations.AlterModelTable(
            name='sitemapcategory',
            table='webhallen_sitemap_category',
        ),
        migrations.AlterModelTable(
            name='sitemaphome',
            table='webhallen_sitemap_home',
        ),
        migrations.AlterModelTable(
            name='sitemapinfopages',
            table='webhallen_sitemap_info_pages',
        ),
        migrations.AlterModelTable(
            name='sitemapmanufacturer',
            table='webhallen_sitemap_manufacturer',
        ),
        migrations.AlterModelTable(
            name='sitemapproduct',
            table='webhallen_sitemap_product',
        ),
        migrations.AlterModelTable(
            name='sitemaproot',
            table='webhallen_sitemap_root',
        ),
        migrations.AlterModelTable(
            name='sitemapsection',
            table='webhallen_sitemap_section',
        ),
        migrations.AlterModelTable(
            name='webhallenjson',
            table='webhallen_json',
        ),
        migrations.AlterModelTable(
            name='webhallenproduct',
            table='webhallen_product',
        ),
        migrations.AlterModelTable(
            name='webhallensection',
            table='webhallen_section',
        ),
    ]
