# Generated by Django 4.2.8 on 2023-12-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(blank=True, help_text='Processor model', null=True)),
                ('family', models.TextField(blank=True, help_text='Processor family', null=True)),
                ('line', models.TextField(blank=True, help_text='Processor line', null=True)),
                ('platform', models.TextField(blank=True, help_text='Processor platform', null=True)),
                ('product_id_tray', models.TextField(blank=True, help_text='Product ID Tray', null=True)),
                ('product_id_boxed', models.TextField(blank=True, help_text='Product ID Boxed', null=True)),
                ('product_id_mpk', models.TextField(blank=True, help_text='Product ID MPK', null=True)),
                ('launch_date', models.DateField(blank=True, help_text='Processor launch date', null=True)),
                ('cpu_core_count', models.IntegerField(blank=True, help_text='Number of CPU cores', null=True)),
                ('thread_count', models.IntegerField(blank=True, help_text='Number of threads', null=True)),
                ('gpu_core_count', models.IntegerField(blank=True, help_text='Number of graphics core', null=True)),
                ('base_clock', models.FloatField(blank=True, help_text='Base clock speed', null=True)),
                ('max_boost_clock', models.FloatField(blank=True, help_text='Max. Boost Clock', null=True)),
                ('all_core_boost_speed', models.FloatField(blank=True, help_text='All Core Boost Speed', null=True)),
                ('l1_cache', models.TextField(blank=True, help_text='L1 Cache', null=True)),
                ('l2_cache', models.TextField(blank=True, help_text='L2 Cache', null=True)),
                ('l3_cache', models.TextField(blank=True, help_text='L3 Cache', null=True)),
                ('_1ku_pricing', models.TextField(blank=True, help_text='1kU Pricing', null=True)),
                ('unlocked_for_overclocking', models.BooleanField(blank=True, help_text='Unlocked for Overclocking', null=True)),
                ('processor_technology', models.TextField(blank=True, help_text='Processor Technology for CPU Cores', null=True)),
                ('cpu_socket', models.TextField(blank=True, help_text='CPU Socket', null=True)),
                ('socket_count', models.IntegerField(blank=True, help_text='Socket Count', null=True)),
                ('pci_express_version', models.TextField(blank=True, help_text='PCI Express® Version', null=True)),
                ('thermal_solution_pib', models.TextField(blank=True, help_text='Thermal Solution PIB', null=True)),
                ('recommended_cooler', models.TextField(blank=True, help_text='Recommended Cooler', null=True)),
                ('thermal_solution_mpk', models.TextField(blank=True, help_text='Thermal Solution MPK', null=True)),
                ('default_tdp', models.TextField(blank=True, help_text='Default TDP', null=True)),
                ('configurable_tdp', models.TextField(blank=True, help_text='AMD Configurable TDP (cTDP)', null=True)),
                ('max_temps', models.TextField(blank=True, help_text='Max. Operating Temperature (Tjmax)', null=True)),
                ('os_support', models.TextField(blank=True, help_text='Operating System Support', null=True)),
                ('max_memory_speed', models.TextField(blank=True, help_text='System Memory Specification', null=True)),
                ('system_memory_type', models.TextField(blank=True, help_text='System Memory Type', null=True)),
                ('memory_channels', models.IntegerField(blank=True, help_text='Memory Channels', null=True)),
                ('per_socket_mem_bw', models.TextField(blank=True, help_text='Per Socket Mem BW', null=True)),
                ('gpu_clock_speed', models.FloatField(blank=True, help_text='Graphics Frequency', null=True)),
                ('graphics_model', models.TextField(blank=True, help_text='Graphics Model', null=True)),
                ('supported_technologies', models.TextField(blank=True, help_text='Supported Technologies', null=True)),
                ('workload_affinity', models.TextField(blank=True, help_text='Workload Affinity', null=True)),
                ('amd_ryzen_ai', models.TextField(blank=True, help_text='AMD Raven™ AI', null=True)),
                ('fips_certification', models.TextField(blank=True, help_text='FIPS Certification', null=True)),
                ('fips_certification_links', models.TextField(blank=True, help_text='FIPS Certification Links', null=True)),
            ],
            options={
                'verbose_name': 'Processor',
                'verbose_name_plural': 'Processors',
                'db_table': 'amd_processors',
                'db_table_comment': 'AMD Processors and their specifications',
                'ordering': ['launch_date'],
            },
        ),
    ]
