# Generated by Django 4.2.8 on 2023-12-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='_1ku_pricing',
            field=models.BigIntegerField(blank=True, help_text='1kU Pricing in dollar cents', null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='all_core_boost_speed',
            field=models.BigIntegerField(blank=True, help_text='All Core Boost Speed in hertz', null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='base_clock',
            field=models.BigIntegerField(blank=True, help_text='Base clock speed in hertz', null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='l1_cache',
            field=models.BigIntegerField(blank=True, help_text='L1 Cache in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='l2_cache',
            field=models.BigIntegerField(blank=True, help_text='L2 Cache in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='l3_cache',
            field=models.BigIntegerField(blank=True, help_text='L3 Cache in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='max_boost_clock',
            field=models.BigIntegerField(blank=True, help_text='Max. Boost Clock in hertz', null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='socket_count',
            field=models.TextField(blank=True, help_text='Socket Count', null=True),
        ),
    ]
