[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
tokio = { version = "1.35.1", features = ["full"] }
tokio-postgres = "0.7.10"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.1"
dotenvy = "0.15.7"
