name: Build and deploy Docker image to GitHub Container Registry

on:
  push:
    branches: [master]
    paths:
      - "main/**"
      - ".github/workflows/docker.yml"
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: sudo snap install hugo --channel=extended/stable
      - run: |
          hugo \
            --gc \
            --minify \
            --panicOnWarning \
            --printI18nWarnings \
            --printMemoryUsage \
            --printPathWarnings \
            --printUnusedTemplates \
            --templateMetrics \
            --templateMetricsHints
        working-directory: main
      - uses: actions/upload-artifact@v3
        with:
          name: public
          path: main/public
          if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Download the artifact from the build job
      - uses: actions/download-artifact@v3
        with:
          name: public
          path: main/public
      - run: ls main/public
      - uses: docker/setup-buildx-action@v3
      - run: docker build -t ghcr.io/thelovinator1/panso:latest .
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/thelovinator1/panso:latest
