name: Run tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        SECRET_KEY: 1234567890
        DEBUG: True
        ADMIN_EMAIL: 4153203+TheLovinator1@users.noreply.github.com
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        REDIS_HOST: localhost
        REDIS_PASSWORD: githubtest
        POSTGRES_PASSWORD: githubtest
        POSTGRES_HOST: 127.0.0.1
        POSTGRES_DB: panso
        POSTGRES_USER: panso
    services:
        postgres:
            image: postgres:16
            env:
                POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
                POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
                POSTGRES_DB: ${{ env.POSTGRES_DB }}
                POSTGRES_USER: ${{ env.POSTGRES_USER }}
            ports:
                - 5432:5432
            options: --health-cmd pg_isready --health-interval 1s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - run: docker run -d -p 6379:6379 --name redis redis:latest /bin/sh -c 'redis-server --appendonly yes --requirepass githubtest'
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - run: pipx install poetry
    - run: poetry install
    - run: poetry run python manage.py collectstatic
    - run: poetry run python manage.py migrate
    - run: poetry run python manage.py test
    - run: docker kill redis
