name: Update Cloudflare IPs for Nginx

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
    update_cloudflare_ips:
        runs-on: ubuntu-latest
        env:
            changed: false
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            # Stolen from https://github.com/linuxserver/docker-mods/tree/swag-cloudflare-real-ip - Thanks :-)
            - name: Update Cloudflare IPs
              run: |
                    echo "" >${GITHUB_WORKSPACE}/nginx/cf_real-ip.conf
                    curl -s "https://api.cloudflare.com/client/v4/ips" | jq -r '.result.ipv4_cidrs[]' | while IFS= read -r line; do
                        echo "set_real_ip_from ${line};" >>${GITHUB_WORKSPACE}/nginx/cf_real-ip.conf
                    done

                    curl -s "https://api.cloudflare.com/client/v4/ips" | jq -r '.result.ipv6_cidrs[]' | while IFS= read -r line; do
                        echo "set_real_ip_from ${line};" >>${GITHUB_WORKSPACE}/nginx/cf_real-ip.conf
                    done

                    ip route | grep -v default | awk '{print $1}' | while IFS= read -r line; do
                        echo "set_real_ip_from ${line};" >>${GITHUB_WORKSPACE}/nginx/cf_real-ip.conf
                    done

            - name: Check for changes
              id: git-check
              run: |
                    git diff --exit-code || echo "changed=true" >> $GITHUB_ENV

            - name: Commit files if changes
              if: env.changed == 'true'
              run: |
                    git config --local user.email "tlovinator@gmail.com"
                    git config --local user.name "Joakim Hellsén"
                    git add ${GITHUB_WORKSPACE}/nginx/cf_real-ip.conf
                    git commit -m "Update Cloudflare IPs"
                    git push
