# Generated by Django 4.2.7 on 2023-12-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eans',
        ),
        migrations.DeleteModel(
            name='HistoricalEans',
        ),
    ]
